name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3.4.4
        with:
          ocaml-compiler: 5.3

      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build @install @doc
