name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3.4.4
        with:
          ocaml-compiler: 5.3

      - run: opam install . --deps-only
      - run: opam install odoc
      - run: opam exec -- dune build @doc

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          folder: _build/default/_doc/_html/
